<?php
$categories = new Application_Model_Base();
echo $this->partial("/base/categories.phtml", array('categories' => $categories->getCategories()));
?>

<h1 class="content_title">Daiktų sąrašas</h1>
<div id="allThings">
</div>
<script type="text/javascript">
    new trades.DragNDrop({
        id:'allThings',
        isDraggable:false, 
        items:<?php echo $this->allthings;?>
    });
</script>

<?php  /*
ob_clean();
echo "<pre>";
var_dump($this->allThings);
die('dump ok');
// */ ?>

