<?php echo $this->form;?>

<div id="imagesBlock" class="imagesBlock">
<?php foreach ($this->images as $image):?>
	<span class="imageContainer"> 
		<img
		id="<?php echo $image->uuid; ?>"
		class="<?php if($image->main == true) echo 'mainImage'; ?>"
		src="/uploads/<?php echo $image->uuid . '.' . $image->ext;?>"
		width="100"
		height="<?php echo $image->height / ($image->width / 100);?>">
		<span class="deleteImage" onclick="deleteImage(dojo.query('img', this.parentNode)[0], '<?php echo $image->uuid; ?>', '<?php echo $image->id;?>')">
		</span>
		<div class="tooltip">
			<span class="arrow"></span>
			<div class="baloon" onclick="setMainImage('<?php echo $image->uuid; ?>', '<?php echo $image->things_id; ?>');">Mark as main</div>
		</div>
	</span> 
<?php endforeach;?>
</div>
