<table id="myThings"  class="thingsTable">
	<thead>
		<tr>
        	<th>Foto</th>
			<th><?php echo 'Title';?></th>
			<th><?php echo 'Description';?></th>
			<th><?php echo 'Wishes';?></th>
                        <th>Delete</th>
		</tr>
	</thead>
</table>

<script type="text/javascript">
	var myThingsCreator = new trades.DragNDrop({
		id:'myThings', 
		itemOnClick:true,
		draggable:true,
		items:<?php echo $this->things;?>
		});
</script>