<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Keičiu.lt</title>

<?php echo $this->headTitle() ?>

<?php echo $this->headMeta() ?>

<?php echo $this->headLink() ?>

<?php echo $this->headStyle() ?>
<?php
$this->dojo()->enable()->setDjConfigOption('parseOnLoad', true)->setDjConfigOption('isDebug', true);
?>

<?php if ($this->dojo()->isEnabled())
{
	$this->dojo()->setLocalPath('/js/dojo/dojo.js')
	->addStyleSheetModule('dijit.themes.claro');
	echo $this->dojo();
}
?>
<?php echo $this->headScript();  ?>
<link rel="stylesheet" href="/css/global.css" />
<link rel="stylesheet" href="/js/dojox/widget/Dialog/Dialog.css" />
<script type="text/javascript" src="/js/trades/trades.js"></script>
</head>
<body class="claro notLoggedBody">

    <div id="header" class="header">
        <div class="logo"></div>
        <div class="title">
            <span>Efektyviausia <br />keitimosi sistema</span>
            <input type="search" name="search" value="Paieška" />
        </div>
        <div class="user_block">
        
        <?php /* ?>
                <input type="text" name="name" />
                <br/>
                <input type="password" name="password" />
            
                <button>Registruotis</button>
                <br/>
                <button>Dėti skelbima</button>
            <?php */ ?>
        </div>
        <div class="menu">
            <?php if (Zend_Auth::getInstance()->hasIdentity()){ ?>
            <a href="/things/mythings"> Mano daiktai </a>
            <a href="/things"> Kurti daikta </a>
            <a href="/trades">  Mainai </a>
            <?php }else{ ?>
            <a href="/account"> Prisijungimas.. </a>
            <?php } ?>
        </div>
    </div>

    <?php if(Zend_Auth::getInstance()->hasIdentity() OR false){
            $userInfo = Zend_Auth::getInstance()->getStorage()->read();
    ?>
        <div class="logoutBlock">
            <a href="/account/profile" class="username"><?php echo $userInfo->username;?></a> | 
                    <a href="/account/logout"><?php echo 'Logout'; ?></a> 
        </div>
        <div class="menu">
            <a href="/things/mythings"> Mano daiktai </a>
            <a href="/things"> Kurti daikta </a>
            <a href="/trades">  Mainai </a>
        </div>
    <?php }else{
                    //echo $this->partial('account/index.phtml', array('loginform' => new Application_Form_LoginForm()));
            }?>


    <div class="content"> <?php echo $this->layout()->content ?>  </div>


    <div class="footer">
        <span>
            &COPY; 2011 Visos teisės saugomos
        </span> 
        <span>
            <a href="#">Rekvizitai</a>
        </span>
        <span>
            <a href="#">Taisyklės</a>
        </span>
    </div>

</body>
</html>
