<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Keiciu.lt</title>

<?php echo $this->headTitle() ?>

<?php echo $this->headMeta() ?>

<?php echo $this->headLink() ?>

<?php echo $this->headStyle() ?>
<?php
$this->dojo()->enable()->setDjConfigOption('parseOnLoad', true)->setDjConfigOption('isDebug', true);
?>

<?php if ($this->dojo()->isEnabled())
{
	$this->dojo()->setLocalPath('/js/dojo/dojo.js')
	->addStyleSheetModule('dijit.themes.claro');
	echo $this->dojo();
}
?>
<?php echo $this->headScript();  ?>
<link rel="stylesheet" href="/css/global.css" />
<link rel="stylesheet" href="/js/dojox/widget/Dialog/Dialog.css" />
<script type="text/javascript" src="/js/trades/trades.js"></script>
</head>
<body class="claro notLoggedBody">

    <div id="header" class="header">
        <span class="logo"></span>
        <div class="title">
            <span style="display: inline-block; vertical-align: middle; padding-right: 10px">Efektyviausia <br />keitimosi sistema</span>
            <span style="display: inline-block" >
                <input type="search" name="search" value="Paieška" />
            </span>
        </div>
        <div class="user_block">
            <?php if (Zend_Auth::getInstance()->hasIdentity()){ ?>
            <?php  $userInfo = Zend_Auth::getInstance()->getStorage()->read(); ?>
                <div class="loged_block">
                    <a href="/"> Pradinis </a>
                    <a href="/things/mythings"> Mano daiktai </a>
                    <a href="/things"> Kurti daikta </a>
                    <a href="/trades">  Mainai </a>
                    <br />
                    <a href="/account/profile" class="username"><?php echo $userInfo->username;?></a> | 
                    <a href="/account/logout"><?php echo 'Logout'; ?></a> 
                </div>
            <?php }else{ ?>
                <div class="not_logged_block">
                    <div style="display: inline-block; padding-right: 10px">
                        <form method="post" action="/account">
                        <input type="text" name="email" value="Vardas"/>
                        <br />
                        <input type="password" name="password" value="Passdf" />
                        <input type="submit" style="display: none;" />
                        </form>
                    </div>
                    <div style="display: inline-block">
                        <button>Registruotis</button>
                        <br />
                        <button>Dėti skelbima</button>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>

    
    <div class="content"> <?php echo $this->layout()->content ?>  </div>


    <div class="footer">
        <span>
            &COPY; 2011 Visos teisės saugomos
        </span> 
        <span>
            <a href="#">Rekvizitai</a>
        </span>
        <span>
            <a href="#">Taisyklės</a>
        </span>
    </div>

</body>
</html>
